=== openwallet-foundation/digital-wallet-and-agent-overviews/viewer/src/assets/case-study.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "CaseStudy",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string",
      "description": "The schema version of the case study JSON entry"
    },
    "reference": {
      "type": "string",
      "description": "The name of the or agent to link it to"
    },
    "headline": {
      "type": "string",
      "description": "Name of the case study"
    },
    "summary": {
      "type": "string",
      "description": "Short summary of the case study"
    },
    "imageUrl": {
      "type": "string",
      "description": "URL to the image of the case study",
      "format": "uri"
    },
    "url": {
      "type": "string",
      "description": "URL to the case study",
      "format": "uri"
    },
    "hashTags": {
      "type": "array",
      "description": "List of hash tags that are relevant for the case study",
      "items": {
        "type": "string"
      }
    }
  },
  "required": [
    "reference",
    "headline",
    "summary",
    "imageUrl",
    "url",
    "hashTags"
  ],
  "additionalProperties": false
}

=== openwallet-foundation/digital-wallet-and-agent-overviews/case-studies/citizenship.json
{
  "$schema": "../viewer/src/assets/case-study.schema.json",
  "reference": "BC Wallet",
  "url": "https://github.com/openwallet-foundation/bifold-wallet",
  "headline": "Digital Citizenship in Canada",
  "summary": "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.",
  "imageUrl": "https://www2.gov.bc.ca/images/discoverBC/PublicEngagements.png",
  "hashTags": ["Digital Identity", "Digital Wallet", "Digital Citizenship"]
}
