=== openwallet-foundation/digital-wallet-and-agent-overviews/viewer/src/assets/dependency.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "Requirement",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string",
      "description": "The schema version of the requirement JSON entry"
    },
    "name": {
      "type": "string",
      "description": "A unique name of the dependency"
    },
    "url": {
      "type": "string",
      "description": "A link to the dependency, ideally to the GitHub repository to fetch the latest version"
    },
    "description": {
      "type": "string",
      "description": "A short description of the dependency"
    },
    "community": {
      "type": "string",
      "description": "A link to interact with the community of the dependency, e.g., a link to the Slack or Discord channel"
    }
  },
  "required": ["name", "url", "$schema"],
  "additionalProperties": false
}

=== openwallet-foundation/digital-wallet-and-agent-overviews/dependencies/bifold.json
{
  "$schema": "../viewer/src/assets/dependency.schema.json",
  "name": "Bifold",
  "url": "https://github.com/openwallet-foundation/bifold-wallet",
  "description": "Aries Mobile Agent React Native - Part of the Aries Bifold effort to provide SSI capabilities in a production ready app.",
  "community": "https://discord.gg/openwalletfoundation"
}
