=== openwallet-foundation/digital-wallet-and-agent-overviews/schema/dependency.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "Dependency",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string",
      "description": "The schema version of the dependency JSON entry"
    },
    "name": {
      "type": "string",
      "description": "A unique name of the dependency"
    },
    "url": {
      "type": "string",
      "description": "A link to the dependency, ideally to the GitHub repository to fetch the latest version"
    },
    "description": {
      "type": "string",
      "description": "A short description of the dependency"
    },
    "license": {
      "type": "string",
      "description": "The license of the dependency"
    },
    "language": {
      "type": "string",
      "description": "The programming language of the dependency"
    },
    "community": {
      "type": "string",
      "description": "A link to interact with the community of the dependency, e.g., a link to the Slack or Discord channel"
    }
  },
  "required": ["name", "url", "$schema", "language"],
  "additionalProperties": false
}

=== openwallet-foundation/digital-wallet-and-agent-overviews/dependencies/credo.json
{
  "$schema": "../viewer/src/assets/dependency.schema.json",
  "name": "Credo",
  "url": "https://github.com/openwallet-foundation/credo-ts",
  "description": "Typescript framework for building decentralized identity and verifiable credential solutions",
  "community": "https://discord.gg/openwalletfoundation",
  "language": "TypeScript",
  "license": "Apache-2.0"
}

=== openwallet-foundation/digital-wallet-and-agent-overviews/data/dependencies/sd-jwt-js.json
{
  "$schema": "../../schemas/dependency.json",
  "name": "SD-JWT-JS",
  "url": "https://github.com/openwallet-foundation-labs/sd-jwt-js",
  "description": "A TypeScript implementation of the Selective Disclosure JWT (SD-JWT) spec.",
  "community": "https://discord.gg/openwalletfoundation",
  "language": "TypeScript",
  "license": "Apache 2.0"
}
